#Application will run on port 8080
server.port=8080

#PostgreSQL Database Configuration
spring.application.name=urlShortener
spring.datasource.url=jdbc:postgresql://localhost:5435/anantpandey
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true