# Application configuration
spring.application.name=urlShortener
server.port=8080
app.base-url=http://localhost:8080

#PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5435/anantpandey
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Execute schema.sql during startup
spring.sql.init.mode=always